version: 0.2

phases:
  pre_build:
    commands:
      - docker build -t sap-frontend .
  build:
    commands:
      - docker images
      - docker run -d --name sap -p 80:80 sap-frontend

artifacts:
  files:
    - '**/*'