version: 0.2

env:
  variables:
    IMG_NAME: "sap-frontend"

phases:
  pre_build:
    commands:
      - docker build -t $IMG_NAME . 

  build:
    commands:
      - docker images
      - docker run -d --name sap -p 80:80 $IMG_NAME

artifacts:
  files:
    - '**/*'