pipeline{
    agent any
    tools{
        jdk 'jdk'
        nodejs 'nodejs25'
    }
    stages {
        stage('clean workspace'){
            steps{
                cleanWs()
            }
        }
        stage('Checkout from Git'){
            steps{
                git branch: 'dev', url: 'https://github.com/gauritambe/sap-classes.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh "npm install"
            }
        }
        stage('Install Tools') {
            steps {
                script {
                    sh '''
                        # Install Trivy if not present
                        if ! command -v trivy &> /dev/null; then
                            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
                        fi
                    '''
                }
            }
        }

        stage('OWASP FS SCAN') {
            steps {
                dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }
            stage('TRIVY FS SCAN') {
            steps {
                sh "trivy fs . > trivyfs.txt"
            }
        }
        stage("Docker Build & Push"){
            steps{
                script{
                   withDockerRegistry(credentialsId: 'docker', toolName: 'docker'){   
                       sh "docker build -t sap-frontend ."
                       sh "docker tag hotstar gauriiitambe/sap-frontend:${date} "
                       sh "docker push gauriiitambe/sap-frontend:${date} "
                    }
                }
            }
        }
        stage("TRIVY"){
            steps{
                sh "trivy image gauriiitambe/sap-frontend:latest > trivyimage.txt" 
            }
        }
        stage('Deploy to container'){
            steps{
                sh 'docker run -d --name frontend -p 80:80 gauriiitambe/sap-frontend:${date}'
            }
        }
        stage('Deploy to Minikube') {
            steps {
                script {
                    sh '''
                        kubectl apply -f ./k8s/namespace.yml 
                        kubectl apply -f ./k8s/deployment.yml 
                        kubectl apply -f ./k8s/service.yml 
                        kubectl get pods -w  # Wait and verify
                        kubectl port-forward service/sap-classes -n sap-classes 80:80 &
                        echo "Port forwarding started on 80"                    
                        '''
                }
            }
        }
    }
}