pipeline{
    agent any
    tools{
        jdk 'jdk'
        nodejs 'nodejs25'
    }
    stages {
        stage('clean workspace'){
            steps{
                cleanWs()
            }
        }
        stage('Checkout from Git'){
            steps{
                git branch: 'dev', url: 'https://github.com/gauritambe/sap-classes.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh "npm ci"
            }
        }
        stage('OWASP FS SCAN') {
            steps {
                dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }
            stage('TRIVY FS SCAN') {
            steps {
                sh "trivy fs . > trivyfs.txt"
            }
        }
        stage("Docker Build & Push"){
            steps{
                script{
                   withDockerRegistry(credentialsId: 'docker', toolName: 'docker'){   
                       sh "docker build -t sap-frontend ."
                       sh "docker tag hotstar gauriiitambe/sap-frontend:${date} "
                       sh "docker push gauriiitambe/sap-frontend:${date} "
                    }
                }
            }
        }
        stage("TRIVY"){
            steps{
                sh "trivy image gauriiitambe/sap-frontend:latest > trivyimage.txt" 
            }
        }
        stage('Deploy to container'){
            steps{
                sh 'docker run -d --name frontend -p 80:80 gauriiitambe/sap-frontend:${date}'
            }
        }
    }
}